sudo: false
language: node_js
node_js:
  - 5

before_install:
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - export PATH=$PWD:$PATH

before_script:
  - bower install

script:
  - npm run test

